replicaCount: 1
image:
  repository: ethereum/client-go
  tag: latest
  pullPolicy: Always
  command: 'geth --testnet --syncmode "fast" --cache=512 --rpc --rpccorsdomain "*" --rpcaddr "0.0.0.0"'
service:
  name: nginx
  type: NodePort
  externalPort: 8545
  internalPort: 8545
data:
  volumeSize: 200Gi
  gcePersistentDiskName: geth-data-testnet
  volumeName: geth-data-testnet
nodeSelector: {cloud.google.com/gke-nodepool: geth-pool}