# Default values for geth-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: ethereum/client-go
  tag: latest
  pullPolicy: Always
  command: 'geth --testnet --fast --cache=512 --rpc --rpccorsdomain "*" --rpcaddr "0.0.0.0"'
service:
  name: nginx
  type: NodePort
  externalPort: 8545
  internalPort: 8545
data:
  volumeSize: 200Gi
  gcePersistentDiskName: geth-data
  volumeName: geth-data
nodeSelector: {cloud.google.com/gke-nodepool: geth-pool}
resources:
  limits:
    cpu: 1m
    memory: 128Mi
  requests:
    cpu: 1m
    memory: 32Mi
